GET https://letterboxed-do-marcio-2-0.vercel.app/filmes

###
POST https://letterboxed-do-marcio-2-0.vercel.app/adicionar-filme
Content-Type: application/json

{
    "nomeDoFilme": "Assassinos da Lua das Flores",
    "genero": "Faroeste/Thriller",
    "duracao": "326",
    "classificacao": "16 anos"
}


###
DELETE https://letterboxed-do-marcio-2-0.vercel.app/apagar-filme/6

###
PUT https://letterboxed-do-marcio-2-0.vercel.app/editar-filme/7
Content-Type: application/json

{
    "nomeDoFilme": "Cães de Aluguel",
    "genero": "Thriller/Crime",
    "duracao": "139",
    "classificacao": "18 anos" 
}